// Header used by providers with no native signing capability (Zapier, Apple
// Shortcuts): the source's generated secret is sent back verbatim in this
// header and compared with a constant-time equality check. Both the server
// verifier (server/utils/signatureVerifier.ts) and the client copy that tells
// the user which header to configure (app/utils/providerSecretCopy.ts, used
// by AddSourceModal.vue's reveal step and SourceCard.vue's ongoing hint)
// import this so the two can never drift apart. Nuxt auto-resolves `shared/`
// for both the app and server layers — import via `#shared`, never a
// relative path.
export const SHARED_SECRET_HEADER = "x-markpost-secret";

// The providers verified via that header (as opposed to GitHub/Stripe, which
// sign with a real HMAC). Defined here rather than only in
// server/utils/signatureVerifier.ts so app/components/SourceCard.vue can
// import the same list — a server file pulls in node:crypto, which breaks
// the client bundle.
export const SHARED_SECRET_PROVIDER_IDS = ["zapier", "shortcuts"] as const;

// Providers whose secret markpost generates itself and reveals exactly once
// (GitHub's HMAC secret plus the shared-secret providers). Same client-safety
// reason as above: the rotate-secret UI (RotateSecretModal.vue / SourceCard.vue)
// needs to know these drive a one-time reveal step, without importing the
// server verifier's node:crypto. server/utils/signatureVerifier.ts consumes
// this as SECRET_BACKED_PROVIDERS so the two never drift.
export const SECRET_BACKED_PROVIDER_IDS = [
  "github",
  ...SHARED_SECRET_PROVIDER_IDS,
] as const;

// Providers whose secret is issued by the provider itself (Stripe) and pasted
// in by the user, rather than generated by markpost — so rotation collects a
// new value from the user instead of revealing a generated one.
export const MANUAL_SECRET_PROVIDER_IDS = ["stripe"] as const;

// Every provider that has a rotatable secret at all. The rotate-secret action
// on a source is offered only for these.
export const ROTATABLE_PROVIDER_IDS = [
  ...MANUAL_SECRET_PROVIDER_IDS,
  ...SECRET_BACKED_PROVIDER_IDS,
] as const;

export function isRotatableProvider(provider: string): boolean {
  return (ROTATABLE_PROVIDER_IDS as readonly string[]).includes(provider);
}

export function isManualSecretProviderId(provider: string): boolean {
  return (MANUAL_SECRET_PROVIDER_IDS as readonly string[]).includes(provider);
}
