import { ApiError } from "./errors";
import {
  generateProviderSecret,
  hashSharedSecret,
  isHashedStorageProvider,
  isManualSecretProvider,
  isSecretBackedProvider,
} from "./signatureVerifier";

// What to persist for a source's provider secret vs. what to hand back to the
// caller once. For hashed-storage providers (Zapier/Shortcuts) these differ:
// only the hash is ever stored, but the plaintext must still be revealed once
// so the user can paste it into that provider's own webhook configuration.
export type ProviderSecretPlan = {
  storedSecret: string | null;
  revealSecret: string | null;
};

function invalidProviderSecretError(): ApiError {
  return new ApiError(
    [
      {
        status: "422",
        title: "Invalid Attribute",
        detail: "ProviderSecret must be a string",
        source: { pointer: "/data/attributes/providerSecret" },
      },
    ],
    422,
  );
}

function missingProviderSecretError(provider: string): ApiError {
  return new ApiError(
    [
      {
        status: "422",
        title: "Invalid Attribute",
        detail: `providerSecret is required for provider "${provider}" — it is issued by ${provider}, not generated by markpost.`,
        source: { pointer: "/data/attributes/providerSecret" },
      },
    ],
    422,
  );
}

function unexpectedProviderSecretError(): ApiError {
  return new ApiError(
    [
      {
        status: "422",
        title: "Invalid Attribute",
        detail:
          "providerSecret is only accepted for a provider that issues its own secret (stripe); markpost generates one for github/zapier/shortcuts.",
        source: { pointer: "/data/attributes/providerSecret" },
      },
    ],
    422,
  );
}

// The single normalization boundary for a caller-supplied providerSecret,
// shared by source creation and secret rotation so both endpoints agree on
// the contract: `undefined` and `null` both mean "not supplied", and any other
// non-string value is rejected. Returning the normalized value keeps the two
// call sites from each having to coalesce `null` themselves.
export function normalizeSuppliedSecret(value: unknown): string | undefined {
  if (value === undefined || value === null) {
    return undefined;
  }

  if (typeof value !== "string") {
    throw invalidProviderSecretError();
  }

  return value;
}

// Manual-secret providers (Stripe) issue their own secret, so the caller must
// supply it. Every other provider (including no provider at all) generates
// its own — a caller-supplied value there would otherwise be silently
// discarded (e.g. a user pasting in their existing GitHub webhook secret,
// expecting it to be used, getting a different generated one instead and a
// permanently-401ing source with no explanation). Reject it instead.
export function validateProviderSecretOrThrow(
  provider: string | null,
  providerSecret: string | undefined,
): void {
  const manualProvider =
    provider && isManualSecretProvider(provider) ? provider : null;

  if (manualProvider && !providerSecret?.trim()) {
    throw missingProviderSecretError(manualProvider);
  }

  if (!manualProvider && providerSecret !== undefined) {
    throw unexpectedProviderSecretError();
  }
}

export function computeProviderSecretPlan(
  provider: string | null,
  suppliedSecret: string | undefined,
): ProviderSecretPlan {
  if (provider && isManualSecretProvider(provider)) {
    // Never echoed back: the user already has this value (they just typed
    // it in), so revealing it in the response would only add a live signing
    // secret to response bodies, proxy logs, and devtools for no benefit.
    const trimmed = suppliedSecret?.trim() ?? null;
    return { storedSecret: trimmed, revealSecret: null };
  }

  if (provider && isSecretBackedProvider(provider)) {
    const plaintext = generateProviderSecret();
    const storedSecret = isHashedStorageProvider(provider)
      ? hashSharedSecret(plaintext)
      : plaintext;
    return { storedSecret, revealSecret: plaintext };
  }

  return { storedSecret: null, revealSecret: null };
}
